### ISSUE TITLE
Hantering av Other

### ISSUE THREAD

**Issue by oskarsoderbom** [JerryRausk/TalentedGamblers-SWA#5]
Någon form av extra information kan behövas för investeringar som landar under Other, t.ex. Casino/strukturerade bettingspel som har dynamiska odds (stryktipset). 

En bilddump är mitt förslag

**Comment by JerryRausk** [comment]
Bets har ett läge där odds inte behöver anges, då förväntas man ange vinstsumman när man stänger bettet sen (istället för att bara ange vinst.

![image](https://github.com/JerryRausk/TalentedGamblers-SWA/assets/37452953/5ebeee0c-de98-452b-8840-2ce990f6254b)
